// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	config "github.com/datadog/stratus-red-team/v2/internal/config"
	mock "github.com/stretchr/testify/mock"
)

// Config is an autogenerated mock type for the Config type
type Config struct {
	mock.Mock
}

// GetKubernetesConfig provides a mock function with no fields
func (_m *Config) GetKubernetesConfig() config.KubernetesConfig {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetKubernetesConfig")
	}

	var r0 config.KubernetesConfig
	if rf, ok := ret.Get(0).(func() config.KubernetesConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.KubernetesConfig)
		}
	}

	return r0
}

// GetTerraformVariables provides a mock function with given fields: techniqueID, overrides
func (_m *Config) GetTerraformVariables(techniqueID string, overrides []string) map[string]string {
	ret := _m.Called(techniqueID, overrides)

	if len(ret) == 0 {
		panic("no return value specified for GetTerraformVariables")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func(string, []string) map[string]string); ok {
		r0 = rf(techniqueID, overrides)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// NewConfig creates a new instance of Config. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *Config {
	mock := &Config{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
