version: 2
updates:
- package-ecosystem: docker
  directory: /
  schedule:
    interval: monthly
  cooldown:
    default-days: 14
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  cooldown:
    default-days: 14
