// Code generated by go generate; DO NOT EDIT.

package attacktechniques
import (
    _ "github.com/datadog/stratus-red-team/v2/internal/attacktechniques/gcp/persistence/backdoor-service-account-policy"
)
