// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	stratus "github.com/datadog/stratus-red-team/v2/pkg/stratus"
)

// StateManager is an autogenerated mock type for the StateManager type
type StateManager struct {
	mock.Mock
}

// CleanupTechnique provides a mock function with no fields
func (_m *StateManager) CleanupTechnique() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CleanupTechnique")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExtractTechnique provides a mock function with no fields
func (_m *StateManager) ExtractTechnique() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExtractTechnique")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRootDirectory provides a mock function with no fields
func (_m *StateManager) GetRootDirectory() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRootDirectory")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetTechniqueState provides a mock function with no fields
func (_m *StateManager) GetTechniqueState() stratus.AttackTechniqueState {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTechniqueState")
	}

	var r0 stratus.AttackTechniqueState
	if rf, ok := ret.Get(0).(func() stratus.AttackTechniqueState); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(stratus.AttackTechniqueState)
	}

	return r0
}

// GetTerraformOutputs provides a mock function with no fields
func (_m *StateManager) GetTerraformOutputs() (map[string]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTerraformOutputs")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTerraformVariables provides a mock function with no fields
func (_m *StateManager) GetTerraformVariables() (map[string]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTerraformVariables")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Initialize provides a mock function with no fields
func (_m *StateManager) Initialize() {
	_m.Called()
}

// SetTechniqueState provides a mock function with given fields: _a0
func (_m *StateManager) SetTechniqueState(_a0 stratus.AttackTechniqueState) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetTechniqueState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(stratus.AttackTechniqueState) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteTerraformOutputs provides a mock function with given fields: outputs
func (_m *StateManager) WriteTerraformOutputs(outputs map[string]string) error {
	ret := _m.Called(outputs)

	if len(ret) == 0 {
		panic("no return value specified for WriteTerraformOutputs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]string) error); ok {
		r0 = rf(outputs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteTerraformVariables provides a mock function with given fields: variables
func (_m *StateManager) WriteTerraformVariables(variables map[string]string) error {
	ret := _m.Called(variables)

	if len(ret) == 0 {
		panic("no return value specified for WriteTerraformVariables")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]string) error); ok {
		r0 = rf(variables)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStateManager creates a new instance of StateManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateManager {
	mock := &StateManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
