package main

import (
	"flag"
	"os"
	"strings"
	"text/template"
)

type TemplateData struct {
	Imports []string
}

const fileTemplate = `// Code generated by go generate; DO NOT EDIT.

package attacktechniques

{{- if .Imports }}
import (
{{- range .Imports }}
    _ "{{ . }}"
{{- end }}
)
{{- else }}
// No techniques imported
{{- end }}
`

func main() {
	var importList string
	flag.StringVar(
		&importList,
		"imports",
		"",
		"Comma-separated list of Go import paths for attack techniques",
	)
	flag.Parse()

	var imports []string
	if importList != "" {
		for _, imp := range strings.Split(importList, ",") {
			imp = strings.TrimSpace(imp)
			if imp != "" {
				imports = append(imports, imp)
			}
		}
	}

  data := TemplateData{
		Imports: imports,
	}

	tmpl := template.Must(template.New("imports").Parse(fileTemplate))

	outputPath := "imports.gen.go"
	f, err := os.Create(outputPath)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		panic(err)
	}

}
