# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StratusRedTeam < Formula
  desc ""
  homepage "https://stratus-red-team.cloud"
  version "2.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DataDog/stratus-red-team/releases/download/v2.0.0/stratus-red-team_2.0.0_Darwin_arm64.tar.gz"
      sha256 "88db0c2f5b12863e22754943aa2062668fa354db2ba1d5d62f12702c57b6e52b"

      def install
        bin.install "stratus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DataDog/stratus-red-team/releases/download/v2.0.0/stratus-red-team_2.0.0_Darwin_x86_64.tar.gz"
      sha256 "0d94fba1c749f52aa352e959df55f266daa871e73659fb18440c2d1556bbdbbc"

      def install
        bin.install "stratus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataDog/stratus-red-team/releases/download/v2.0.0/stratus-red-team_2.0.0_Linux_arm64.tar.gz"
      sha256 "2e3c5bc194ae8e54398ae3e3ed04d7ef42c38f77f58f537218011ab9531797ff"

      def install
        bin.install "stratus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DataDog/stratus-red-team/releases/download/v2.0.0/stratus-red-team_2.0.0_Linux_x86_64.tar.gz"
      sha256 "f3911f5db5112b4139c83ea254b20885964fdb88956f48e2eadb2d69d631401e"

      def install
        bin.install "stratus"
      end
    end
  end
end
