# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StratusRedTeam < Formula
  desc ""
  homepage "https://stratus-red-team.cloud"
  version "2.18.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/DataDog/stratus-red-team/releases/download/v2.18.0/stratus-red-team_Darwin_x86_64.tar.gz"
      sha256 "33b8c447bd5805005f69b2100beefc064d94599d2a7743c07d3ebdfbd01a832f"

      def install
        bin.install "stratus"

        # Install shell completions
        generate_completions_from_executable(bin/"stratus", "completion", shells: [:bash, :fish, :zsh], base_name: "stratus")
      end
    end
    on_arm do
      url "https://github.com/DataDog/stratus-red-team/releases/download/v2.18.0/stratus-red-team_Darwin_arm64.tar.gz"
      sha256 "2da813f2e7023c84a7932140afda5e578222ce32906c19c784362b0e0be6bb31"

      def install
        bin.install "stratus"

        # Install shell completions
        generate_completions_from_executable(bin/"stratus", "completion", shells: [:bash, :fish, :zsh], base_name: "stratus")
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DataDog/stratus-red-team/releases/download/v2.18.0/stratus-red-team_Linux_x86_64.tar.gz"
        sha256 "1307009f737790596a79a0e8e5ccceb7fa3208f321b4328fcd33b267c26ad956"

        def install
          bin.install "stratus"

          # Install shell completions
          generate_completions_from_executable(bin/"stratus", "completion", shells: [:bash, :fish, :zsh], base_name: "stratus")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DataDog/stratus-red-team/releases/download/v2.18.0/stratus-red-team_Linux_arm64.tar.gz"
        sha256 "65eaf721d49f7d12e3b0fc3e8099fd4bd6c05b15c91e68367ae5716fc23cc794"

        def install
          bin.install "stratus"

          # Install shell completions
          generate_completions_from_executable(bin/"stratus", "completion", shells: [:bash, :fish, :zsh], base_name: "stratus")
        end
      end
    end
  end
end
