issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/stratus-red-team:ref:refs/heads/main

claim_pattern:
  event_name: push
  ref: refs/heads/main
  ref_protected: "true"
  job_workflow_ref: DataDog/stratus-red-team/.github/workflows/release.yml@refs/heads/main

permissions:
  contents: read
