issuer: https://token.actions.githubusercontent.com

subject_pattern: repo:DataDog/stratus-red-team:ref:refs/(heads/main|tags/.*)

claim_pattern:
  event_name: push
  ref: refs/(heads/main|tags/.*)
  # ref_protected: "true" # Can't set this because GH API is not reliable on tag protection status. Cf https://github.com/orgs/community/discussions/142985
  job_workflow_ref: DataDog/stratus-red-team/.github/workflows/release.yml@refs/(heads/main|tags/.*)

permissions:
  contents: write
  pull_requests: write
