issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/stratus-red-team:ref:refs/(heads/main|tags/.*)

claim_pattern:
  event_name: push
  ref: refs/(heads/main|tags/.*)
  ref_protected: "true"
  job_workflow_ref: DataDog/stratus-red-team/.github/workflows/release.yml@refs/(heads/main|tags/.*)

permissions:
  contents: read
  pull_requests: write
