// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	stratus "github.com/datadog/stratus-red-team/pkg/stratus"
)

// StateManager is an autogenerated mock type for the StateManager type
type StateManager struct {
	mock.Mock
}

// ExtractTechniqueTerraformFile provides a mock function with given fields:
func (_m *StateManager) ExtractTechniqueTerraformFile() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRootDirectory provides a mock function with given fields:
func (_m *StateManager) GetRootDirectory() {
	_m.Called()
}

// GetTechniqueOutputs provides a mock function with given fields:
func (_m *StateManager) GetTechniqueOutputs() (map[string]string, error) {
	ret := _m.Called()

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTechniqueState provides a mock function with given fields:
func (_m *StateManager) GetTechniqueState() stratus.AttackTechniqueState {
	ret := _m.Called()

	var r0 stratus.AttackTechniqueState
	if rf, ok := ret.Get(0).(func() stratus.AttackTechniqueState); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(stratus.AttackTechniqueState)
	}

	return r0
}

// SetTechniqueState provides a mock function with given fields: _a0
func (_m *StateManager) SetTechniqueState(_a0 stratus.AttackTechniqueState) {
	_m.Called(_a0)
}

// WriteTerraformOutputs provides a mock function with given fields: outputs
func (_m *StateManager) WriteTerraformOutputs(outputs map[string]string) error {
	ret := _m.Called(outputs)

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]string) error); ok {
		r0 = rf(outputs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// initialize provides a mock function with given fields:
func (_m *StateManager) initialize() {
	_m.Called()
}
